Sp1
IlyaYP/devops pull request #1
Opened 2021-12-28 14:52 UTC by IlyaYP

2021-12-28 21:10 UTC, Bazys requested changes
Работа сделана на 99%
Осталось научиться штатно завершаться по сигналам: syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT.
За одно при реализации этого пункта правильно будет задействована работа с контекстом

2021-12-28 21:10 UTC, Bazys commented on internal/rtmetrics.go
> +		<-time.After(interval)
если в cmd/agent/main.go переменную сразу определить как  pollInterval := 2*time.Second то не нужно будет тут преобразований

2021-12-28 21:10 UTC, Bazys commented on storage/inmemory/memstorage.go
> +	sync.RWMutex
вот это правильное решение. (хоть это пока и не проходили)

2021-12-28 21:10 UTC, Bazys commented on storage/inmemory/memstorage.go
> +func (s *Storage) PutMetric(ctx context.Context, MetricType, MetricName, MetricValue string) error {
не вижу применения context.Context в данной функции
и в последующих тоже

2021-12-28 21:10 UTC, Bazys commented on storage/interface.go
> +type MetricStorage interface {
в данном случае нет необходимости выносить в отдельный файл

2021-12-29 06:54 UTC, IlyaYP commented
 Добрый день, Рафаэль! В задании сказано что в гитхабе переписку вести нельзя, так что отвечаю тут.Замечания, основные, исправил. С уважением,Илья Супрун. 29.12.2021, 00:10, "Bazys" ***@***.******@***.*** requested changes on this pull request.Работа сделана на 99%Осталось научиться штатно завершаться по сигналам: syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT.За одно при реализации этого пункта правильно будет задействована работа с контекстомIn cmd/agent/main.go:>  package main
 
-func main() {}
+import (
+	"github.com/IlyaYP/devops/internal"
+	"time"
+)
+
+func main() {
+	pollInterval := 2
+	reportInterval := 10
+	messages := make(chan string, 200)
+
+	go internal.NewMonitor(pollInterval, messages)
а где тут обработкаАгент должен штатно завершаться по сигналам: syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT.In cmd/server/handlers/handlers.go:> +
+		err = t.Execute(w, data)
+		check(err)
+	}
+}
+
+//GET http://localhost:8080/value/counter/testSetGet33
+//GET http://localhost:8080/value/counter/PollCount
+func GetHandler(st *inmemory.Storage) http.HandlerFunc {
+	return func(w http.ResponseWriter, r *http.Request) {
+		k := strings.Split(r.URL.String(), "/") // TODO: Chi not work in tests, so using old method
+		//if err := st.PutMetric(context.Background(), chi.URLParam(r, "MType"),
+		//	chi.URLParam(r, "MName"), chi.URLParam(r, "MVal")); err != nil {
+		v, err := st.GetMetric(context.Background(), k[2], k[3])
+		if err != nil {
+			if err.Error() == "wrong type" {
в принципе для учебного проекта можно и так сравнивать.Но для промышленной разработкаи лучше заводить custom errorshttps://yourbasic.org/golang/create-error/In cmd/server/handlers/handlers.go:> @@ -0,0 +1,106 @@
+package handlers
в данном пакете у тебя три функции, все в качестве параметра принимают inmemory.Storageсоответственно прям напрашивается структура в которой в качестве поля этот самый storage.И реализовать три функции к этой структуре.(Это как вариант развития на будущее)In cmd/server/main.go:> @@ -1,3 +1,60 @@
 package main
 
-func main() {}
+import (
+	"context"
+	"fmt"
+	"github.com/IlyaYP/devops/cmd/server/handlers"
+	"github.com/IlyaYP/devops/storage/inmemory"
+	"github.com/go-chi/chi/v5"
+	"net/http"
+)
+
+func testStore(st *inmemory.Storage) {
зачем этот код в main модуле?In cmd/server/main.go:> +		fmt.Println(v)
+	}
+	ret := st.ReadMetrics(context.Background())
+	fmt.Println(ret)
+
+}
+
+func main() {
+	st := inmemory.NewStorage()
+	//testStore(st)
+
+	r := chi.NewRouter()
+	r.Get("/", handlers.ReadHandler(st))
+	r.Get("/value/{MType}/{MName}", handlers.GetHandler(st))
+	r.Post("/update/{MType}/{MName}/{MVal}", handlers.UpdateHandler(st))
+	http.ListenAndServe(":8080", r)
тут аналогично, не вижуСервер должен уметь штатно завершаться по сигналам: syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT.In cmd/server/main_test.go:> @@ -0,0 +1,23 @@
+package main
+
+import (
+	"github.com/IlyaYP/devops/storage/inmemory"
+	"testing"
+)
+
+func Test_testStore(t *testing.T) {
нет, тестировать надо не стор, а ответы сервераIn internal/rtmetrics.go:> +	StackSys,
+	Sys,
+	RandomValue gauge
+	PollCount counter
+}
+
+func NewMonitor(duration int, messages chan string) {
+	var rtm runtime.MemStats
+	//var rm runTimeMetrics
+	PollCount := 0
+	s1 := rand.NewSource(time.Now().UnixNano())
+	r1 := rand.New(s1)
+
+	var interval = time.Duration(duration) * time.Second
+	for {
+		<-time.After(interval)
если в cmd/agent/main.go переменную сразу определить как pollInterval := 2*time.Second то не нужно будет тут преобразованийIn storage/inmemory/memstorage.go:> @@ -0,0 +1,88 @@
+package inmemory
+
+import (
+	"context"
+	"fmt"
+	"github.com/IlyaYP/devops/storage"
+	"strconv"
+	"sync"
+)
+
+var _ storage.MetricStorage = (*Storage)(nil) // Q: Вот это для чего? я ещё не изучил (
+
+type Storage struct {
+	sync.RWMutex
вот это правильное решение. (хоть это пока и не проходили)In storage/inmemory/memstorage.go:> +
+var _ storage.MetricStorage = (*Storage)(nil) // Q: Вот это для чего? я ещё не изучил (
+
+type Storage struct {
+	sync.RWMutex
+	mtr map[string]map[string]string
+} //{mtr: make(map[string]map[string]string)}
+
+func NewStorage() *Storage {
+	s := Storage{mtr: make(map[string]map[string]string)}
+	s.mtr["counter"] = make(map[string]string)
+	s.mtr["gauge"] = make(map[string]string)
+	return &s
+}
+
+func (s *Storage) PutMetric(ctx context.Context, MetricType, MetricName, MetricValue string) error {
не вижу применения context.Context в данной функциии в последующих тожеIn storage/interface.go:> @@ -0,0 +1,9 @@
+package storage
+
+import "context"
+
+type MetricStorage interface {
в данном случае нет необходимости выносить в отдельный файл—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.You are receiving this because you authored the thread.Message ID: ***@***.***>

2021-12-29 08:10 UTC, Bazys reviewed
в приципе все ок, но в любом случае надо через платформу подавать на код-ревью заявку

2021-12-29 08:10 UTC, Bazys commented on storage/inmemory/memstorage.go
> +var _ storage.MetricStorage = (*Storage)(nil) // Q: Вот это для чего? я ещё не изучил (
Это небольшой хак, проверка на то, что структурные функции удовлетворяют интерфейсу.
В принципе обычно делают конструктор, который возвращает интерфейс на основе струтуры

2021-12-29 12:52 UTC, Bazys approved these changes

2021-12-29 13:12 UTC, merged